### ISSUE TITLE
Example using  antron/promise

### ISSUE THREAD

**Issue by idkjs** [aantron/dream#147]
Is it possible to use the aantron/promise.git lib in a dream project so maybe you could use the same promise library on front/back? 

Thanks for this great work you have shared.

**Comment by aantron** [comment]
The issue is that on native there isn't an I/O library to work with aantron/promise, unless you wrap Lwt or have Lwt's engine [drive](https://github.com/aantron/repromise_lwt) aantron/promise. Neither one of these is practical in the immediate term. If you'd like to try or help with developing this, I suggest continuing discussion in aantron/promise#75 since this issue is more about developing aantron/promise than about Dream.
