### ISSUE TITLE
Template error messages can be unintuitive

### ISSUE THREAD

**Issue by outkine** [aantron/dream#153]
Template errors become confusing very quickly. Example:
```ocaml
let render =
  <html>
  <body>
%   [1; 2; 3] |> List.map (fun n -> (
      <p><%i n %><p>
%   ))
  </body>
  </html>
```
As a beginner, I expect this to work, because the OCaml code is 'returning' the generated HTML. But I get an error:
```
Error: This expression has type unit but an expression was expected of type
         int list
```
Okay, so I begin to understand that these control flow statement need to be `unit` (I'm not sure if this is in the documentation, but it probably should be). So I try
```ocaml
let render =
  <html>
  <body>
%   ([1; 2; 3] |> List.map (fun n -> (
      <p><%i n %><p>
%   )));
  </body>
  </html>
```
But still an error:
```
Error: This expression has type unit list
       but an expression was expected of type unit
       because it is in the left-hand side of a sequence
```
(forgive me if I'm wrong about this) but I don't intuitively see how this is a `unit list` and not `unit`. Finally, this works:
```ocaml
let render =
  <html>
  <body>
%   ([1; 2; 3] |> List.map (fun n -> (
      <p><%i n %><p>
%   ))) |> ignore;
  </body>
  </html>
```
I think this templating system is very powerful, but that comes at a certain cost -- it takes some messing with to get right. I think that the more that Dream can help point the developer in the right direction here, the better.

**Comment by aantron** [comment]
I'll add to the documentation to try to make some of this clearer.

The core issue in this particular case is:

> (forgive me if I'm wrong about this) but I don't intuitively see how this is a `unit list` and not `unit`.

You should use [`List.iter`](https://ocaml.org/api/List.html#VALiter) and not [`List.map`](https://ocaml.org/api/List.html#VALmap). You would have had the same error message

```
Error: This expression has type unit list
       but an expression was expected of type unit
       because it is in the left-hand side of a sequence
```

anywhere in OCaml outside the templating system, in any context that expected `unit`, and you used `List.map` instead of `List.iter`. By using `List.map`, you are "converting" each integer to `()`, and making a list `[(); (); ()]`, so it is a `unit list`. If you used `List.iter`, you would just have the program iterate over the list, returning no new list and just `()` after the iteration.

This is shown in some examples

https://github.com/aantron/dream/blob/ae3b5d24d35a77c79d718228b1c415ba7db4c6af/example/h-sql/sql.eml.ml#L25-L26

but, indeed, the documentation should both make it clearer that things should end with `;` and return `unit`, and show an example with `List.iter` very early on to "guide" readers in that direction. #87 is related.
