### ISSUE TITLE
Middleware to strip trailing slashes

### ISSUE THREAD

**Issue by roddyyaga** [aantron/dream#24]
Thanks for writing this, it's very exciting!

It would be useful to have a middleware to strip trailing slashes, so you can define one handler for `/foo/bar` and `/foo/bar/`. I can't see how to write one with the currently exposed functions for `request`s. Maybe more general functionality for rewriting paths would also be good.

**Comment by aantron** [comment]
@roddyyaga Thanks for the issue! I will expose the path manipulation functions for the first release. That is indeed an oversight.

In case you'd like to do it sooner, it can be done with a couple of internal functions:

```ocaml
let strip_trailing_slashes : Dream.middleware =
    fun inner_handler request ->

  let request = Obj.magic request in
  Dream__pure.Inmost.internal_path request
  |> Dream.drop_empty_trailing_path_component
  |> fun path -> Dream__pure.Inmost.with_path path request
  |> Obj.magic
  |> inner_handler
```

The `: Dream.middleware` annotation would normally not be necessary, but I added it for a bit more safety since this code heavily abuses `Obj.magic` to access the internal types.

**Comment by aantron** [comment]
With the linked commits, the middleware now looks like

```ocaml
let count_requests inner_handler request =
  let path = Dream.drop_trailing_slash (Dream.path request) in
  inner_handler (Dream.with_path path request
```

There is an oddity with dropping the trailing slash of `/`, the root path, because the "smallest" path a request can be for, AFAICT, is `/`, and dropping that `/` creates a request that cannot be matched to a route at all. I don't know if it that needs special handling to be usable.

**Comment by aantron** [comment]
> There is an oddity with dropping the trailing slash of `/`, the root path, because the "smallest" path a request can be for, AFAICT, is `/`, and dropping that `/` creates a request that cannot be matched to a route at all. I don't know if it that needs special handling to be usable.

Reflecting on this, it might be better, where possible, to add a trailing `/` if it is missing, rather than drop trailing `/` if present &mdash; a bit like the redirects done by many servers, AFAIK.
