### ISSUE TITLE
Use `multipart_form` instead of `multipart-form-data`

### ISSUE THREAD

**Issue by dinosaure** [aantron/dream#3]
I know that I come like someone who want to push his projects but I really think that you probably want to use [`multipart_form`](https://github.com/dinosaure/multipart_form) instead of [`multipart-form-data`](https://github.com/cryptosense/multipart-form-data) when the latter does not stream contents - which limits your usage.

If you are interested by that , I can propose a PR if you want :+1:.

**Comment by aantron** [comment]
@dinosaure Thanks! I indeed am interested in `multipart_form`, and have seen it preferred in an Opium discussion when I was first working with file uploads before starting Dream.

I have not yet fully evaluated the two, and chose to start with `multipart-form-data` mainly because its interface seemed easier to deal with quickly for prototyping purposes, since Dream is in an alpha state. Concerning streaming, it appears that `multipart-form-data` does emit chunks, and does accept a stream as the data source. I did not verify yet whether it waits to load its entire input stream, which would, of course, be a major flaw for Dream's purposes, if that is the case. I *did* observe several other flaws (at least that's how they seemed to me):

https://github.com/aantron/dream/blob/f50145650f26cbbd8ce474b0b42570a1c48b940e/src/middleware/upload.ml#L70-L76

I would welcome a PR in principle. However, in the interest of respecting your time, I'd like to delay at first, so that I have a chance to look more closely before asking/agreeing for you to proceed :) I will probably spend a few days finishing up the examples and docs for an "alpha1" release. After that, I will be doing passes through all the parts of Dream, and then I will take many close looks at uploads again :)

**Comment by dinosaure** [comment]
Ok, let me know when you did your choice :) then, if you want to improve some details, I'm able to spend my time to improve the library if you want :+1:.

**Comment by aantron** [comment]
@dinosaure I took a good look at `multipart_form`, and I'd be happy to merge a PR switching to it. The current parser is in [`src/middleware/upload.ml`](https://github.com/aantron/dream/blob/master/src/middleware/upload.ml). It uses a pretty hacky state type which is defined in Dream's core module, because it is a mutable part of requests (the same as the request body stream is inherently mutable):

https://github.com/aantron/dream/blob/54e228d65c4598e1985d8d81504bbeb804dd1de1/src/pure/inmost.ml#L33-L59

You're welcome to replace these with anything that you need. They are both completely internal &mdash; all that matters is to convert to the [upload pull interface](https://aantron.github.io/dream/#streaming-upload), and offer some way of passing I/O errors up to the interface caller.

By the way, if you have any comments on the interface itself, it is also subject to discussion and change :)

**Comment by dinosaure** [comment]
Close by #45, thanks!
