### ISSUE TITLE
Is there a release with #302 in near future?

### ISSUE THREAD

**Issue by pyx** [aantron/dream#319]
I am working on a project and found out that [Caqti](https://ocaml.org/p/caqti/latest/doc/Caqti_type/index.html) on opam is 2.1.1 with different API.
Thanks.

**Comment by hypirion** [comment]
For people getting stuck by this, you can do `opam pin dream --dev-repo` as a stopgap solution until a new version is released.

**Comment by hannesm** [comment]
I've been wondering as well... So, Caqti update was merged end of October 2023 (at the time of writing that is more than half a year ago). The last activity on the git has been on January 18th 2024 - which is 4 months ago. There are people trying out OCaml and dream, and get stuck with the current state of what is released to the opam-repository (see as example https://hypirion.com/musings/getting-ocaml-through-the-eye-of-a-needle).

I was wondering what the maintenance status of dream is? I observe that the maintenance and release engineering work is done by @aantron, but there are quite a few users and active participants (though it seems nobody else has rights to the git repository, or is entitled to cut releases). Are there releases planned, or will it stay in this limbo as-is? Would it be sensible to either fork it then or move it to the github.com/ocaml-community organization?

Thanks for all the hard work on it. I'd really like to see it being used more widely, esp. without a ton of "pin those commits, since they work with recent versions of ..".

**Comment by aantron** [comment]
#302 was just released in [Dream 1.0.0~alpha6](https://github.com/aantron/dream/releases/tag/1.0.0-alpha6), which is now installable from opam.

**Comment by aantron** [comment]
Thanks for the kick and to @hypirion for offering a workaround command. @hannesm I got bogged down in some issues related to multicore, but I decided to rest, just maintain Dream, and yes, it was originally planned to make it more of a community project, so to move on that.

**Comment by pyx** [comment]
> #302 was just released in [Dream 1.0.0~alpha6](https://github.com/aantron/dream/releases/tag/1.0.0-alpha6), which is now installable from opam.

> Thanks for the kick and to @hypirion for offering a workaround command. @hannesm I got bogged down in some issues related to multicore, but I decided to rest, just maintain Dream, and yes, it was originally planned to make it more of a community project, so to move on that.

Thank you.

**Comment by hannesm** [comment]
Thanks @aantron for cutting the release.
