### ISSUE TITLE
Can't build dream on M1 Mac

### ISSUE THREAD

**Issue by maxRN** [aantron/dream#328]
I was trying to compile dream locally and while I was able to install all dependencies, running the examples isn't possible.

This is what I did, following docs/CONTRIBUTING.md:
1. `git clone https://github.com/aantron/dream.git --recursive`
2. `cd dream`
3. `opam switch create . 4.14.1 --no-install`
4. `make deps`
5. `cd examples/1-hello`
6. `dune exec ./hello.exe` --> This fails

```shell
Entering directory '/Users/maxrn/code/dream'
File "src/cipher/random.ml", line 25, characters 20-37:
25 |   Cstruct.to_string (random_buffer n)
                         ^^^^^^^^^^^^^^^^^
Error: This expression has type string but an expression was expected of type
         Cstruct.t
```

Dune version: 3.16.0
opam version: 2.1.5
ocaml version: 4.14.1

**Comment by aantron** [comment]
Thanks for the report! @oemmerson diagnosed this as that mirage-crypto, a dependency of Dream, has been updated in a breaking fashion in its recent 1.0.0 release. The easiest immediate solution is to pin it to a lower version with `opam pin mirage-crypto 0.11.3 --no-action` and then try installing Dream.

@oemmerson has also proposed a fix in #331 by constraining Dream to require older versions of mirage-crypto. However, we'd actually like to upgrade to 1.0.0, including because it has some quite nice changes, so I've proposed the upgrade in #334 instead. I'll like to do some more testing before merging, but you should be able to try it now by running the dev commands from a checkout of the `mirage-crypto-1` branch.

Thanks @maxRN, @oemmerson!
