### ISSUE TITLE
Phoenix LiveView-like feature inside Dream

### ISSUE THREAD

**Issue by dangdennis** [aantron/dream#59]
Would a Phoenix LiveView-like feature best be a part of the dream framework or live as a plug-in or library?

To those unknown, LiveView is the Elixir Phoenix library that allows servers to dynamically render HTML and serve it over websockets.

A few other frameworks exist that are beginning to do the same: Ruby Hotwire and Haskell IHP.

Another option may be to create an HTMX-compatible dream middleware much like how Sihl is doing so for a more dynamic UX without heavy JS.

Is the GitHub discussion available for this repo? This isn’t really an issue, but more a discussion.

**Comment by aantron** [comment]
I think it's better to keep it as a library for now. However, I'd be very happy to coordinate development with it, support it on the Dream side, and link to it.

My concern is that Dream has only one maintainer right now (me :P) and people might contribute a lot of interesting things, but then not stick around to really finish and maintain them. Meanwhile there is already a ton of work for me to finish only the core of Dream to a truly high level of quality. So I'd like to coordinate with multiple people independently and see what develops over time. Later, Dream might have some kind of stable team of people working on it (probably informal), and it will be clearer what can be upstreamed, if needed.

If you're interested in developing this, you may want to see example [**`w-live-reload`**](https://github.com/aantron/dream/tree/master/example/w-live-reload#files) (perhaps you already have), contributed by @tmattio. It's, of course, not the same thing, but it's vaguely relevant :)

I'll be happy to link to a repo as proposed in https://github.com/aantron/dream/pull/58 and suggested in [Contributing](https://github.com/aantron/dream/tree/f12e0e0e4bcd3208ef31826ae6b5e3ad1dd19327#contributing), and offer any other support to make it visible, usable, etc.

> Is the GitHub discussion available for this repo? This isn’t really an issue, but more a discussion.

I disabled it for now because issues are still fine for basic discussion, and it's one less thing to deal with this early. However, if you think it should be enabled, please let me know.

**Comment by aantron** [comment]
I'm closing this issue for now to keep the tracker tidy, but please feel free to comment, and reopen the issue if needed.

**Comment by tcoopman** [comment]
I just came across this: https://erratique.ch/software/hc - https://discuss.ocaml.org/t/tutorial-full-stack-web-dev-in-ocaml-w-dream-bonsai-and-graphql/9963/13

> Hc declares dynamic web pages by using HTML data attributes to seamlessly update the page with HTML fragments requested from the server.

> Using hypertext as the interaction substrate keeps logic on the server and, in the simplest cases, reduces front-end client code to custom CSS animations and inclusion of a generic JavaScript driver.

It might be nice to look into for dream

**Comment by cemerick** [comment]
Yeah, the docs describe it as being inspired by htmx. FWIW, that's the "front end" I'm using in my current project (mostly using htmx's websocket support and its "out of band" DOM updates); it's been _very_ pleasant.
