### ISSUE TITLE
Enabling Vscode OCaml intellisence with Esy in examples

### ISSUE THREAD

**Issue by dangdennis** [aantron/dream#64]
Hey all. If you’re new to the OCaml system like myself, your Vscode and the example projects may need some additional dependencies to get the official extension to work. Otherwise, you may get these errors.

![](https://cdn.discordapp.com/attachments/439062744105484288/848005347191947264/Screen_Shot_2021-05-28_at_9.06.39_PM.png)

To enable proper auto completion and go-to definition, open each example directory as a root project. And add these two lines to your esy.json to get the vscode ocaml extension to work.
```
        "@opam/ocaml-lsp-server": "*",
        "@opam/ocamlfind-secondary": "*",
```

**Comment by dangdennis** [comment]
I may verify this afternoon and make a PR myself.

**Comment by aantron** [comment]
Thanks @dangdennis!

If you will make a PR, I suggest adding a blurb about this to [esy example](https://github.com/aantron/dream/tree/master/example/w-esy#files), and then mentioning in the [Hello, world!](https://github.com/aantron/dream/tree/master/example/1-hello#files), somewhere, that people should go to the esy example for things like this. Hello, world! already links to the esy example for general background on esy. If that later turns out to be not enough, I/we will see what else can/should be done to make this more visible.

I would tend to hesitate to pervasively add this to all examples (for instance, in case you were considering that), because this is (I guess?) VSCode specific. To ansewr your question on Discord, I do use VSCode, but not OCaml-LSP. It seems like this kind of knowledge probably belongs in the esy or OCaml-LSP docs, and hopefully will get spread around the community over time, but we can indeed help in this repo by making it more visible now.

**Comment by dangdennis** [comment]
I did naively think of adding it too all relevant examples that used Esy. I'll make a PR to add the lsp suggestion inside the esy example. 

Is that cool?

**Comment by dangdennis** [comment]
Hehe, really want to see Dream succeed and become as easy as starting up a RoR, Go, Express server.

**Comment by aantron** [comment]
> I did naively think of adding it too all relevant examples that used Esy. I'll make a PR to add the lsp suggestion inside the esy example.
> 
> Is that cool?

Yes, please :)

**Comment by aantron** [comment]
Another good place to add it may be in [`example/2-middleware/esy.json`](https://github.com/aantron/dream/blob/cc691bd37ae2c82e32d84be693119ce713d1c1d9/example/2-middleware/esy.json), which is used by the quick start script, as well as a brief mention in its ["outro" text](https://github.com/aantron/dream/blob/cc691bd37ae2c82e32d84be693119ce713d1c1d9/example/quickstart.sh#L64).

**Comment by aantron** [comment]
Upon further reflection, @dangdennis, I think your approach was right &mdash; it's better to just add this to all the examples. However, if it eases work for you, I suggest you add it to only one, for instance 2-middleware, and test that everything then works out of the box for you with the quick start script. Then, I'll add it to the rest of the examples in a separate commit and list you in Co-authored-by, since I'm already used to doing tedious work like that :)

**Comment by dangdennis** [comment]
I’ll add it to 2-middleware and to the esy example.

**Comment by dangdennis** [comment]
today I learned that you can add comments inside esy.json. Makes sense if esy doesn't expect a spec-compliant json file.

**Comment by aantron** [comment]
IIRC that is also true of `bsconfig.json`, can't check immediately.

**Comment by aantron** [comment]
I believe this was solved by #65 and follow-on commits linked to it. Thanks!

cc @ManasJayanth, as I think this may need documenting on the esy side.

**Comment by ManasJayanth** [comment]
I have added a small notes right away in the docs. If there's more to add, happy to discuss and accept a PR.
https://github.com/esy/esy/pull/1317/files

**Comment by aantron** [comment]
Thanks @ManasJayanth!
