### ISSUE TITLE
(newb) Why does "w-fullstack-rescript" not use rescript for server side

### ISSUE THREAD

**Issue by yatesco** [aantron/dream#70]
Hi there, https://github.com/aantron/dream/tree/master/example/w-fullstack-rescript claims "ReScript syntax is not available for the server side". 

Can I clarify why that is as ReScript works fine on the server side?

**Comment by aantron** [comment]
Is there a way to compile ReScript to native code? Dream is a native-only framework at the moment, though it is possible to get it working on Node, in principle.

If ReScript compiles to native code, then I should convert the example to use ReScript on the server (or I will merge a PR).

If it doesn't compile to native code, I'll clarify the example to specify native code rather than just "server side."

**Comment by aantron** [comment]
I went with option 2 for now, specifying that ReScript doesn't compile to native. If that's wrong, please let me know!

**Comment by yatesco** [comment]
Nope, I'm being a doofus and getting confused between  `rescript` and `reason`
