### ISSUE TITLE
(newb) "4-counter" example and race conditions?

### ISSUE THREAD

**Issue by yatesco** [aantron/dream#71]
Hi there,

Are middleware applied in an exclusive and atomic way?

If not, is the example in https://github.com/aantron/dream/tree/master/example/4-counter open to a race condition because the `!counter` and `+ 1` could be interrupted by another thread?

I realise these are demos(!) and so I'm not throwing aspersions(!), I'm trying to educate myself :-).

**Comment by aantron** [comment]
No worries :) OCaml native code runs in a single thread by default for now (just like JS, actually, which is one of the reasons OCaml/Reason/ReScript are such natural choices for compile-to-JS languages).

So, there is no way to interrupt the `!counter + 1` and the `:=`.

Despite using only one thread, there is still a very high degree of concurrency, because of the use of promises. Also just like in much of JS.

**Comment by yatesco** [comment]
Gotcha - thanks :-).
